Repository AjouCola/FE-CLIENT, pull requests merged in 2022-04, with the labels that each got.

#14 [Feat] 회원가입 이용약관
  src/components/atoms/checkbox/index.tsx
  src/components/atoms/checkbox/styles.ts
  src/components/molecules/section/PolicySection/index.tsx
  src/components/molecules/section/PolicySection/styles.ts
  src/components/molecules/section/index.tsx
  src/components/templates/signUp/policy/index.tsx
  src/components/templates/signUp/policy/styles.ts
  src/constants/singupPolicy.ts
  src/pages/signup/index.tsx
Labels: feat, css

#15 [Refactor] 회원가입 페이지 에러 해결 및 불필요한 로직 제거
  public/github_button.svg
  public/google_button.svg
  src/components/Layout.tsx
  src/components/atoms/button/index.tsx
  src/components/atoms/button/login.tsx
  src/components/atoms/button/styles.tsx
  src/components/atoms/button/submit.tsx
  src/components/atoms/checkbox/index.tsx
  src/components/atoms/input/index.tsx
  src/components/molecules/input/index.tsx
  src/components/molecules/input/styles.tsx
  src/components/molecules/modal/majorModal.tsx
  src/components/molecules/section/PolicySection/index.tsx
  src/components/organisms/Navigation/AuthNavigation.tsx
  src/components/organisms/Navigation/styles.ts
  src/components/templates/signIn/index.tsx
  src/components/templates/signUp/index.tsx
  src/components/templates/signUp/index.type.ts
  src/components/templates/signUp/policy/index.tsx
  src/components/templates/signUp/policy/styles.ts
  src/components/templates/signUp/styles.tsx
  src/pages/signup/policy/index.tsx
  src/styles/global.tsx
  src/styles/globals.css
Labels: feat, fix, refactor, css

#16 [Style] 상단 내비게이션 스타일 수정
  src/assets/icon/heart.svg
  src/assets/icon/logo.svg
  src/assets/icon/search.svg
  src/assets/icon/userDefault.svg
  src/components/atoms/icon/userDefault.tsx
  src/components/atoms/input/styles.tsx
  src/components/molecules/header/index.tsx
  src/components/molecules/header/styles.tsx
  src/components/molecules/searchBar/index.tsx
  src/components/molecules/searchBar/styles.tsx
  src/constants/index.tsx
  src/store/index.ts
  src/styles/theme.ts
  src/utils/api/Auth.ts
Labels: css

#22 [refactor] write UI
  public/all.svg
  public/all_check.svg
  public/edit.svg
  public/edit_check.svg
  public/preview.svg
  public/preview_check.svg
  src/components/Layout.tsx
  src/components/atoms/button/submit.tsx
  src/components/atoms/hashtagChip/index.tsx
  src/components/atoms/hashtagChip/styles.tsx
  src/components/atoms/input/index.tsx
  src/components/molecules/editor/styles.tsx
  src/components/molecules/previewer/index.tsx
  src/components/molecules/previewer/styles.tsx
  src/components/organisms/Navigation/index.tsx
  src/components/organisms/markdowneditor/styles.tsx
  src/components/templates/signUp/index.tsx
  src/components/templates/write/index,type.ts
  src/components/templates/write/index.tsx
  src/components/templates/write/styles.ts
  src/styles/theme.ts
  yarn.lock
Labels: feat, fix, refactor, css

#25 [Refactor] 디자인 시스템 개편
  src/components/atoms/button/auth.tsx
  src/components/atoms/button/login.tsx
  src/components/atoms/button/submit.tsx
  src/components/atoms/checkbox/styles.ts
  src/components/atoms/hashtagChip/styles.tsx
  src/components/atoms/icon/userDefault.tsx
  src/components/atoms/input/styles.tsx
  src/components/atoms/todoCheckBox/index.tsx
  src/components/molecules/boardType/boardCard/index.tsx
  src/components/molecules/boardType/boardCard/styles.ts
  src/components/molecules/boardType/boardPreviewItem/styles.ts
  src/components/molecules/boardType/boardSimpleItem/styles.ts
  src/components/molecules/header/styles.tsx
  src/components/molecules/input/styles.tsx
  src/components/molecules/modal/majorModal.tsx
  src/components/molecules/modal/styles.tsx
  src/components/molecules/searchBar/styles.tsx
  src/components/molecules/section/PolicySection/styles.ts
  src/components/molecules/section/index.tsx
  src/components/molecules/sidebar/styles.tsx
  src/components/organisms/markdowneditor/styles.tsx
  src/components/templates/signUp/policy/styles.ts
  src/components/templates/signUp/styles.tsx
  src/components/templates/write/styles.ts
  src/styles/theme.ts
Labels: refactor, css

#24 [Refactoring] Add NextPage type in each pages
  src/pages/board/[id].tsx
  src/pages/board/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signIn/index.tsx
  src/pages/signUp/index.tsx
  src/pages/todolist/index.tsx
  src/pages/write/index.tsx
Labels: refactor

#27 [Feat] 게시물 상세 페이지UI 구현
  public/comment.svg
  public/comment_Big.svg
  public/header.png
  public/heart.svg
  public/heart_Big.svg
  public/left_arrow.svg
  public/right_arrow.svg
  public/visit.svg
  src/components/organisms/boardContent/index.tsx
  src/components/organisms/comment/index.tsx
  src/components/organisms/signUpForm/index.tsx
  src/pages/board/[id].tsx
  src/styles/theme.ts
Labels: feat, css

#28 [Style] board content
  src/components/atoms/hashtagChip/styles.tsx
  src/components/organisms/boardContent/index.tsx
  src/components/organisms/boardContent/styles.ts
  src/pages/board/[id].tsx
Labels: css

#29 [Hotfix] eslint error 해결
  .eslintrc.json
  .vscode/settings.json
  src/components/atoms/button/auth.tsx
  src/components/atoms/button/index.tsx
  src/components/atoms/button/login.tsx
  src/components/atoms/button/submit.tsx
  src/components/atoms/icon/userDefault.tsx
  src/components/molecules/boardType/boardCard/index.tsx
  src/components/molecules/boardType/boardCard/styles.ts
  src/components/molecules/boardType/boardPreviewItem/index.tsx
  src/components/molecules/boardType/boardPreviewItem/styles.ts
  src/components/molecules/boardType/boardSimpleItem/index.tsx
  src/components/molecules/boardType/boardSimpleItem/styles.ts
  src/components/molecules/header/styles.tsx
  src/components/molecules/modal/index.tsx
  src/components/molecules/modal/majorModal.tsx
  src/components/molecules/modal/styles.tsx
  src/components/organisms/Navigation/AuthNavigation.tsx
  src/components/organisms/comment/index.tsx
  src/components/organisms/signUpForm/index.tsx
  src/components/organisms/signUpForm/styles.tsx
  src/components/organisms/signUpInput/index.tsx
  src/components/organisms/signUpInput/styles.tsx
  src/pages/_middleware.ts
  src/pages/board/index.tsx
  src/pages/index.tsx
  src/pages/portal.tsx
  src/pages/signIn/index.tsx
  src/pages/signUp/index.tsx
  src/pages/signUp/policy/index.tsx
  src/pages/todolist/index.tsx
  src/pages/write/index.tsx
  src/types/board/index.ts
  src/types/signIn/index.ts
  src/types/signUp/index.ts
  src/types/write/index.ts
  tsconfig.json
Labels: bug, hotfix
