Repository AjouCola/FE-CLIENT, pull requests merged in 2022-05, with the labels that each got.

#31 [Style] 드롭다운 검색창 스타일
  src/components/molecules/searchBar/index.tsx
  src/components/molecules/searchBar/styles.tsx
Labels: css

#33 [Feat] 로그인 버튼 생성 및 oath 링크 수정
  src/components/atoms/button/login.tsx
  src/constants/index.tsx
  src/pages/signIn/index.tsx
  src/pages/signUp/index.tsx
  src/utils/api/core/index.ts
Labels: feat, fix, css

#34 [Feat] 아주 모각코 게더타운을 위한 소켓 구성
  .gitignore
  package.json
  src/components/molecules/sidebar/index.tsx
  src/pages/gather/index.tsx
  src/store/gatherSocket.ts
  yarn.lock
Labels: feat

#32 [Feat] TopButton 구현
  package-lock.json
  public/up.svg
  src/components/Layout.tsx
  src/components/atoms/button/index.tsx
  src/components/atoms/topbutton/index.tsx
  yarn.lock
Labels: feat

#35 [Feat] TodoList 페이지
  src/assets/icon/folder_primary.svg
  src/assets/icon/left_arrow_primary.svg
  src/assets/icon/right_arrow_primary.svg
  src/components/Layout.tsx
  src/components/atoms/calenderDayElement/index.tsx
  src/components/atoms/calenderDayElement/styles.tsx
  src/components/atoms/todoCheckBox/draggable.tsx
  src/components/atoms/todoCheckBox/index.tsx
  src/components/atoms/todoCheckBox/styles.tsx
  src/components/molecules/calender/index.tsx
  src/components/molecules/calender/styles.tsx
  src/components/molecules/todoArea/index.tsx
  src/components/molecules/todoArea/styles.ts
  src/components/molecules/todoMenuModal/index.tsx
  src/components/molecules/todoMenuModal/styles.tsx
  src/pages/todolist/index.tsx
  src/store/index.ts
  src/store/todo.ts
  src/styles/todolist/index.ts
Labels: css

#37 [Feat] 쿠키 유틸
  package.json
  src/components/molecules/header/index.tsx
  src/components/molecules/header/styles.tsx
  src/utils/cookie.ts
  yarn.lock
Labels: feat

#41 [Hotfix] husky를 이용한 lint-staged 적용
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .husky/pre-commit
  .lintstagedrc.js
  .prettierrc.json
  package.json
  src/components/organisms/signUpForm/index.tsx
  src/constants/singupPolicy.ts
  src/styles/Home.module.css
  yarn.lock
Labels: hotfix

#42 feat: add skeleton code for todo list api
  src/pages/todolist/index.tsx
  src/store/index.ts
  src/utils/api/Todo.ts
Labels: feat, refactor

#43 [Style] home
  src/assets/images/home_banner.svg
  src/components/Layout.tsx
  src/components/molecules/calender/styles.tsx
  src/components/molecules/homeBoardItem/index.tsx
  src/components/molecules/homeBoardItem/styles.ts
  src/components/organisms/homeSection/boardSection.tsx
  src/components/organisms/homeSection/todoSection.tsx
  src/pages/index.tsx
  src/pages/todolist/index.tsx
  src/styles/globals.css
  src/styles/todolist/index.ts
Labels: css

#45 [Hotfix] socket 디펜던시 추가
  package.json
  yarn.lock
Labels: hotfix

#46 [hotfix] lint code
  src/components/molecules/homeBoardItem/styles.ts
Labels: hotfix

#48 style: add profile dropdown menu
  src/assets/icon/notify.svg
  src/components/molecules/header/index.tsx
  src/components/molecules/header/styles.tsx
  src/components/molecules/profileDropdownItem/index.tsx
  src/components/molecules/profileDropdownItem/styles.ts
  src/components/molecules/profileDropdownTab/index.tsx
  src/components/molecules/profileDropdownTab/styles.ts
  src/components/organisms/Navigation/index.tsx
  src/components/organisms/profileDropdown/index.tsx
  src/components/organisms/profileDropdown/styles.ts
  src/utils/api/Auth.ts
Labels: css

#49 [Style] 헤더 반응형 스타일 추가
  src/components/molecules/header/index.tsx
  src/components/molecules/header/styles.tsx
  src/components/molecules/modal/mobileSearchModal.tsx
  src/components/molecules/searchBar/index.tsx
  src/components/molecules/searchBar/styles.tsx
  src/components/molecules/sidebar/styles.tsx
  src/components/organisms/notifyDropdown/index.tsx
  src/components/organisms/notifyDropdown/styles.ts
  src/constants/index.tsx
Labels: css

#50 [Style] 헤더 반응형 사이즈 조절
  src/assets/icon/logo.svg
  src/assets/icon/userDefault.svg
  src/components/atoms/icon/userDefault.tsx
  src/components/molecules/header/index.tsx
  src/components/molecules/header/styles.tsx
  src/components/molecules/searchBar/styles.tsx
Labels: css

#55 [Hotfix] 테스트 게시글 ID 추가
  src/pages/board/[id].tsx
Labels: fix, hotfix

#56 [Style] 회원가입 페이지 이메일 로딩 스피너 추가
  src/components/atoms/button/auth.tsx
  src/components/organisms/signUpForm/index.tsx
  src/components/organisms/signUpInput/index.tsx
  src/components/organisms/signUpInput/styles.tsx
Labels: feat, css

#60 [Style] 게시글 리스트 스타일 수정
  src/assets/icon/board_detail_type.svg
  src/assets/icon/board_grid_type.svg
  src/assets/icon/board_list_type.svg
  src/components/organisms/boardPageTemplate/index.tsx
  src/components/organisms/signUpInput/styles.tsx
  src/styles/board/index.ts
  src/styles/globals.css
Labels: css

#61 [Style] 마이페이지 정보수정 스타일
  src/components/atoms/card/styles.tsx
  src/pages/mypage/edit.tsx
  src/pages/mypage/index.tsx
  src/styles/mypage/index.ts
Labels: css

#63 [Feat] 댓글 삭제 기능 추가
  src/components/molecules/editor/CommentViewer.tsx
  src/pages/board/[id].tsx
  src/utils/api/Comment.ts
Labels: fix
